Allow omitted optional close tags in HTMLSimpleDOM
adobe/brackets pull request #12057
Opened 2016-01-06 21:22 UTC by jscissr

Fixes #7257.

2016-01-06 21:55 UTC, jscissr commented
There is still a bug that I just found:

```
<div>
  <p>hello
</div>
```

When you edit `hello`, the text node disappears from the live preview. At the moment I have no idea why.

2016-01-11 19:39 UTC, jscissr commented
I have now pushed the change discussed in https://github.com/jscissr/brackets/commit/107d81bb58bbbea85b25f5fe037d2ba1dcb5a525.
Travis is failing because of rate limits.

2016-08-25 23:04 UTC, zaggino commented
This looks good to me & has tests, but I'm no Live Preview expert.
Can someone review/merge this @adobe/brackets-committers ?

2016-10-20 19:42 UTC, petetnt submitted a review, later dismissed

2016-10-20 20:12 UTC, petetnt commented
Hi @jscissr,

sorry for taking so long to address this and thanks for this great PR. Address the few comments I made above so we can get this merged ASAP. If not, we can merge this and fix those small issues later too.

2016-10-20 20:14 UTC, petetnt requested changes

2016-10-20 20:14 UTC, petetnt commented on src/language/HTMLSimpleDOM.js
> +    // TODO: handle optional start tags
This TODO is already handled?

2016-10-20 20:14 UTC, petetnt commented on src/language/HTMLSimpleDOM.js
> +      dd: true,
Add `dt` here too, it's not completely correct behavior but without it it flickers around syntax error every other keypress. See the https://github.com/adobe/brackets/issues/7257 case for an example

2016-10-20 20:18 UTC, petetnt commented
Hi @jscissr,

sorry for taking so long with this one! We really do appreciate this fix!

Would you mind fixing those two small things? Otherwise we can just merge this and fix the small issues later too.

2016-10-25 19:35 UTC, petetnt commented on src/language/HTMLSimpleDOM.js
> +    // TODO: handle optional start tags
Well that's weird, never though of omitting start tags. IMHO definitely not worth it.

2016-10-25 19:44 UTC, petetnt commented on src/language/HTMLSimpleDOM.js
> +    // TODO: handle optional start tags
Hmm, I guess it can be there for a future reminder, but it's out of scope of this PR.

2016-10-25 20:04 UTC, jscissr commented on src/language/HTMLSimpleDOM.js
> +      dd: true,
I don't see any flickering, but I changed it anyway.

2016-10-25 20:07 UTC, petetnt approved these changes

2016-10-25 20:08 UTC, petetnt commented
Thanks @jscissr for this great contribution!

2016-10-25 20:08 UTC, merged