Added ARIA Code hints v2
adobe/brackets pull request #12471
Opened 2016-05-29 20:34 UTC by Coder206

With the aria-atomic, aria-activedescendant and aria-flowto. Has been compared to WYSIWYG for ARIA, its a match. @RaymondLim Plus added "none" to aria-autocomplete

2016-06-10 00:52 UTC, ingorichter commented
Great addition. Thank you. Would you mind changing the formatting back to the previous style? BTW: did you sign the contributor license agreement (CLA)?

2016-06-10 10:45 UTC, Coder206 commented
@ingorichter I am not sure what you mean by "previous style". Yes I think I did!

2016-06-10 17:04 UTC, ingorichter commented
Looking at the diff, you can see that the previous formatting was different. Every entry was in one line.

2016-06-10 21:54 UTC, Coder206 commented
@ingorichter Ok!

2016-06-17 13:46 UTC, Coder206 commented
@ingorichter I can't tell if this is an error on my part. I don't think changing a format can fail a build...

2016-06-22 01:53 UTC, Coder206 commented
@ingorichter Is my work done here?

2016-07-22 13:08 UTC, twang2218 commented
@Coder206 The code style are different. Many irrelevant code have been touched in the first commit. Here is the screenshot.

<img width="1157" alt="2016-07-22 23 03 50" src="https://cloud.githubusercontent.com/assets/6299096/17057909/ac413d14-5060-11e6-9e2b-5b2edaf62197.png">

Did you turn on the code beautify/format? Maybe you can turn them off and restore the original format, and try commit again. Thanks.

2016-07-22 13:18 UTC, Coder206 commented on src/extensions/default/HTMLCodeHints/HtmlAttributes.json
> +    "accesskey":                { "attribOption": [], "global": "true" },
@twang2218 I thought I did... I am not sure what is going on.

2016-08-30 13:38 UTC, twang2218 commented
@Coder206 I send a pull request in your repo to you to fix the format issue some days ago, could you merge it, so this issue can be fixed?

2016-08-30 13:52 UTC, Coder206 commented
@twang2218 Ok sounds good.

2016-08-30 18:08 UTC, ficristo commented
@twang2218 you need to sign the CLA http://dev.brackets.io/brackets-contributor-license-agreement.html
While indirectly, you still have modified the source.

@ingorichter do you have time to review this?

2016-08-30 19:15 UTC, twang2218 commented
@ficristo ok. It's done.

2016-08-30 19:35 UTC, Coder206 commented
@ficristo I am quite sure I have filled it out. What makes you think I didn't?

2016-09-23 16:55 UTC, ficristo commented
@Coder206 Could you solve the merge conflicts?

2016-09-23 19:36 UTC, Coder206 commented
@ficristo I am very confused as to what I have to do know. I have a enabled edits from maintainers.

2016-09-24 06:06 UTC, ficristo commented
On your local branch you should merge master in it, solve eventual conflicts and push again your changes.

2016-09-24 13:17 UTC, Coder206 commented
@ficristo Ok I am wondering why this PR wasn't merged beforehand.

2016-10-02 18:16 UTC, Coder206 commented
Ping!

2016-10-02 18:31 UTC, ficristo commented
If your ping is about this not be merged, keep in mind that at the moment Adobe is focused on Dreamweaver so there is much help there.

Personally I was thinking @ingorichter would have reviewed this.
Then as some weeks ago, I was hoping a 1.8 release would come out, and I was waiting it before reviewing your PR myself.

For the conflicts they happen: you should resolve them.

2016-10-02 19:16 UTC, Coder206 commented
@ficristo Done!

2016-10-02 23:09 UTC, zaggino requested changes
You need to fix the diff, you merged master incorrectly removing `autocomplete` options: 
![image](https://cloud.githubusercontent.com/assets/1067319/19024541/650a57e4-8951-11e6-825a-cda36be947c1.png)

2016-10-03 01:39 UTC, Coder206 commented
Changes made :)

2016-10-03 02:45 UTC, merged

2016-10-03 02:45 UTC, zaggino commented
:+1: thanks @Coder206

2016-10-03 03:52 UTC, ingorichter commented
Sorry. I somehow missed that