add font-display property
adobe/brackets pull request #12785
Opened 2016-09-16 01:46 UTC by samuelcarreira

Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

****** Values **********
auto
The font display strategy is defined by the user agent.
block
Gives the font face a short block period and an infinite swap period.
swap
Gives the font face no block period and an infinite swap period.
fallback
Gives the font face an extremely small block period and a short swap period.
optional
gives the font face an extremely small block period and no swap period.

2016-09-16 01:48 UTC, zaggino approved these changes

2016-09-16 01:48 UTC, zaggino commented
@samuelcarreira You need to sign http://dev.brackets.io/brackets-contributor-license-agreement.html before I can merge this in.

2016-09-17 08:21 UTC, ficristo requested changes
I think you should sort the values alphabetically.
It seems to me that only `inherit` should be always the last value

2016-09-17 08:22 UTC, ficristo approved these changes

2016-09-17 08:23 UTC, ficristo commented
I should have read all the description...

2016-09-17 08:23 UTC, merged