Disabled context menu items for unsaved files
adobe/brackets pull request #12806
Opened 2016-09-29 16:44 UTC by mansimarkaur

Fixes #11763

2016-09-29 17:32 UTC, ficristo commented
Have you checked what other editors do in these cases?
In general you need some jsdocs.
@petetnt @zaggino could someone of you review?

2016-09-29 17:54 UTC, petetnt requested changes
LGTM sans couple of missing pieces of JSDoc

2016-09-29 17:54 UTC, petetnt commented on src/command/DefaultMenus.js
> +    function _setContextMenuItemsVisible(enabled, items) {
Needs JSDoc

2016-09-29 17:54 UTC, petetnt commented on src/command/DefaultMenus.js
> +    function _setMenuItemsVisible() {
Needs JSDoc

2016-09-29 17:56 UTC, petetnt commented
Thanks for this great PR @mansimarkaur! Tested against latest master and it works great.

Could you add few small pieces of JSDoc for the new methods and maybe simple unit test for the functionality? (`it should disable context menu items when not present` and `it should not disable context menu items when present`)

👍

2016-10-02 16:23 UTC, mansimarkaur commented
@petetnt  sure, I'll add the required changes.

2016-10-27 17:54 UTC, mansimarkaur commented
@petetnt Could you please help me with the tests? I was thinking of adding tests in the `test/Menu-test.js` file. Please let me know if it's right?

2016-10-27 20:30 UTC, petetnt commented
@mansimarkaur `test/Menu-test.js` sounds like a good place.

Any specific things you need help with the tests? The structure should could be something like:

```
it("it should disable context menu items when file doesn't exist ", function () {
  // runs create a new file
  // opens context menu
  // checks that all the items are disabled
})
```
```
it("it should disable context menu items when file doesn't exist ", function () {
  // runs create a new file
  // opens context menu
  // checks that all the items are disabled
})
```

```
it("it should enable context menu items when file does exist ", function () {
  // runs create a new file and saves it
  // opens context menu
  // checks that all the items are enabled
})
```

For example check `DocumentCommandHandlers` tests to see how the working set can be manipulated.

2016-12-24 15:39 UTC, Denisov21 commented
+1 big idea!

2017-02-13 19:25 UTC, ficristo commented
This needs more work. Closing for now.

2017-03-01 19:04 UTC, petetnt approved these changes

2017-03-01 19:05 UTC, petetnt commented
LGTM sans tests, merging this and will open another issue for the tests as per https://github.com/adobe/brackets/issues/11763#issuecomment-283425634

Thanks for this great contribution @mansimarkaur and sorry for taking so long! 

PS: did this test totally flake? https://travis-ci.org/adobe/brackets/builds/206719157 CLA checked manually just in case.

2017-03-01 19:05 UTC, merged