Fix for #11801
adobe/brackets pull request #12830
Opened 2016-10-12 14:52 UTC by jerrak0s

When the input field for font is not valid set the preferences in the default font size.

2016-10-12 18:36 UTC, ficristo requested changes
This doesn't seem the right fix.
As suggested by @MiguelCastillo in the opening issue, have you tryed to add the pattern attribute to the html?
Something like `pattern="^[\d\.]+(px|em)$"`

2016-10-12 19:21 UTC, petetnt commented
Thanks for contributing to Brackets @jerrak0s!

I think the pattern attribute could work, not sure if there's a premade size validation regexp though but the example @ficristo gave should be close enough after adding `rem`s and so on. 

@jerrak0s you can see the documentation on `pattern` here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern

2016-10-12 21:29 UTC, jerrak0s commented
My intention was to fix the wrong value in the `textfield` Font Size: after wrong input.
So when i save something wrong in the font Size, that is not saved.
![capture](https://cloud.githubusercontent.com/assets/3514710/19328379/0487a254-90dc-11e6-9bbb-0b3235de8cd8.PNG)

2016-10-13 09:00 UTC, petetnt commented
@jerrak0s Yup, and it's a good thing to do! With the `pattern` attribute however, you can ensure that users cannot write invalid values at all to the field 👍

2017-02-13 19:24 UTC, ficristo commented
This needs more work. Closing for now.
The issue #11801 is still open.

2017-02-13 19:24 UTC, closed without merging