Issue #12859 Keyboard modifiers support for simulateKeyEvent
adobe/brackets pull request #12863
Opened 2016-10-31 19:47 UTC by haslam22

Added support for sending additional arguments to simulateKeyEvent, e.g. modifiers such as `ctrlKey: true` or any other value supported by `KeyboardEventInit`.

2016-11-25 08:47 UTC, petetnt commented
Sorry about being so slow with this, been swamped with work as of late. I'll review this on Sunday / Monday. 

Again, apologies for taking so long!

2016-11-25 13:12 UTC, haslam22 commented
No worries! Thanks for putting aside time to review this.

> On 25 Nov 2016, at 08:47, Pete Nykänen <notifications@github.com> wrote:
> 
> Sorry about being so slow with this, been swamped with work as of late. I'll review this on Sunday / Monday.
> 
> Again, apologies for taking so long!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-11-27 16:27 UTC, petetnt requested changes
Some review comments, mostly looks good to me! Needs an unit test though 👍

2016-11-27 16:27 UTC, petetnt commented on test/spec/SpecRunnerUtils.js
> +        if(typeof options === 'undefined') {
We can use `Object.assign` to make this a bit easier:

``` js
var defaultOptions = {
  options.view = doc.defaultView;
  options.bubbles = true;
  options.cancelable = true;
  options.keyIdentifier = key;
};
var newOptions = Object.assign({}, options, defaultOptions});
var oEvent = new KeyboardEvent(event, newOptions);
```

2016-11-27 16:27 UTC, petetnt commented on test/spec/SpecRunnerUtils.js
> +        }
Nit: trailing whitespace

2016-12-01 14:54 UTC, haslam22 commented
Made the requested changes, and provided a unit test. Had to pop it in a new file, `SpecRunnerUtils-test`, hope that's fine. Let me know if anything else needs to be changed, thanks!

2016-12-06 21:01 UTC, petetnt requested changes

2016-12-06 21:01 UTC, petetnt commented on test/spec/SpecRunnerUtils.js
> +        var newOptions = Object.assign({}, options, defaultOptions);
It was brought up in another PR that using `Object.assign` actually brokes the Linux version due to using an age old CEF which doesn't support it 😢 

If you could change this to the previous format then this one is ready to be merged

2016-12-07 00:08 UTC, haslam22 commented on test/spec/SpecRunnerUtils.js
> +        var newOptions = Object.assign({}, options, defaultOptions);
No problem at all, reverted to the old version. 👍

2016-12-22 08:40 UTC, petetnt commented
I'll try and test this out for the final time today and then merge it in, LGTM so far :1st_place_medal:

2016-12-22 11:16 UTC, haslam22 commented
Great, thanks!

> On 22 Dec 2016, at 08:40, Pete Nykänen <notifications@github.com> wrote:
> 
> I'll try and test this out for the final time today and then merge it in, LGTM so far 🥇
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-12-23 08:22 UTC, petetnt commented on test/spec/SpecRunnerUtils.js
>       * Simulate key event. Found this code here:
We can remove these comments now as the implementation is different

2016-12-23 08:22 UTC, petetnt requested changes

2016-12-23 08:22 UTC, petetnt commented on test/spec/SpecRunnerUtils.js
>       * Simulate key event. Found this code here:
We can remove these comments now as the implementation is different

2016-12-23 08:23 UTC, petetnt commented
Okay, one more nitpick and then it's ready to go 👍  Great work @haslam22!

2016-12-23 15:06 UTC, haslam22 commented
Woops, forgot to update that part. Should be all good now.

2016-12-23 15:07 UTC, petetnt approved these changes

2016-12-23 15:07 UTC, merged

2016-12-23 15:07 UTC, petetnt commented
Thanks for this great contribution @haslam22!