Add "replace all" button when doing find and replace
adobe/brackets pull request #12988
Opened 2016-12-17 18:21 UTC by amrelnaggar

For #11126.

cc: @ficristo

2016-12-20 20:00 UTC, ficristo requested changes
LGTM, only some nits to fix.

2016-12-20 20:00 UTC, ficristo commented on src/nls/root/strings.js
> +    "BUTTON_REPLACE_ALL"                : "Replace All\u2026",
Remove `\u2026`

2016-12-20 20:00 UTC, ficristo commented on src/search/FindInFilesUI.js
> +    */
Indent one space more the jsdocs.

2016-12-20 20:00 UTC, ficristo commented on src/search/FindInFilesUI.js
> +                    _finishReplaceBatch(FindInFiles.searchModel);
There is a JSLint warning here: `'_finishReplaceBatch' was used before it was defined.`
After the `var _findBar = null;` aboce, you can add a new line and add a declaration, something like:
```js
var _findBar = null;

// Forward declaration.
var _finishReplaceBatch;
```

2016-12-20 20:00 UTC, ficristo commented on src/search/FindReplace.js
> +        if(all === null){
Add one space after the `if` and one before the `{` to fix some JSLint warnings.

2016-12-22 18:04 UTC, ficristo approved these changes

2016-12-22 18:05 UTC, ficristo commented
LGTM, thank you.

2016-12-22 18:05 UTC, merged

2016-12-23 07:59 UTC, petetnt commented
Great job @amrelnaggar!