[WIP] JS refactor->rename for named variables, members and functions in a single file
adobe/brackets pull request #13047
Opened 2017-01-18 10:14 UTC by swmitra

This PR implements "rename" functionality in JS mode to enable intelligent rename feature by using Terns scope analysis and inference functions. Renaming across multiple files has been intentionally blocked for the time being as we are not analyzing all the JS files in current project root right now. Once the other PR #11948 is merged, we can leverage on the JS analysis in node and include all files to build symbol table. 
The rename function works by selecting a variable def/ref or placing cursor in and using Ctrl+R. 

Know issues
--------------
In a particular case Tern inference engine is picking up wrong hit. For example - 
 `function fn1(error) {` 
   `     error.a = "abc";`
   `     var a = "test";`
   `     console.log(a);`
 `}`
If we try to rename `a` in line 3 or 4 , Tern picks up fake ref from line 2 as well. 

Yet to be done
----------------

- [ ] To enable context menu option for rename
- [ ] Update JS doc and minor code cleanup  
- [ ] Couple of bug fixes ( one mentioned above and another to center primary selection )

2017-01-19 10:58 UTC, petetnt requested changes
Some initial comments here. Great work so far!

2017-01-19 10:58 UTC, petetnt commented on src/extensions/default/JavaScriptCodeHints/main.js
> +            if (!session || session.editor.getModeForSelection() !== "javascript") {
Can `session.editor` be `null` or `undefined`? Most likely not, but might be worth checking out.

2017-01-19 10:58 UTC, petetnt commented on src/extensions/default/JavaScriptCodeHints/ScopeManager.js
> +            fileInfo = {type: MessageIds.TERN_FILE_INFO_TYPE_FULL,
Nit: Have we used some kind of style for multiline objects? The indentation looks a bit weird, I would prefer
```js
fileInfo = {
  type: MessageIds.TERN_FILE_INFO_TYPE_FULL,
  name: path,
  offsetLines: 0,
  text: filterText(session.getJavascriptText())
};

2017-01-19 10:58 UTC, petetnt commented on src/extensions/default/JavaScriptCodeHints/main.js
> +                if (response.hasOwnProperty("promise")) {
Is there are case where response wouldn't have a `promise`? `requestFindRefs` looks like it's pretty null safe, but might be good to guard with `response && response.hasOwn...`

2017-01-19 10:58 UTC, petetnt commented on src/extensions/default/JavaScriptCodeHints/main.js
> +                    response.promise.done(handleFindRefs).fail(function () {
Can we use `then` and `catch` to align the old Deferred syntax with the more modern Promises/A+ syntax?

2017-01-19 10:58 UTC, petetnt commented on src/extensions/default/JavaScriptCodeHints/main.js
> +                function isInSameFile(obj) {
Can be shortened to `return obj && obj.file === refsResp.file`

2017-01-19 10:58 UTC, petetnt commented on src/extensions/default/JavaScriptCodeHints/main.js
> +                if (refsResp && refsResp.refs && refsResp.refs.refs) {
Random comment: `refsResp.refs.refs` looks kinda silly 👯

2017-01-19 10:58 UTC, petetnt commented on src/extensions/default/JavaScriptCodeHints/tern-worker.js
> +                        var response = {type: MessageIds.TERN_REFS,
NIT: Same thing here with the new lines and objects

2017-01-19 12:05 UTC, swmitra commented
Thanks a lot @petetnt for the quick review. I will try to address the comments asap. I would urge all of you to use the feature as well and let me know if it's helpful.

2017-01-19 12:49 UTC, ficristo requested changes

2017-01-19 12:49 UTC, ficristo commented on src/base-config/keyboard.json
> +        "Ctrl-R"
I believe on macOS this is translated to Cmd+R which is used to reload Brackets with Extensions.

2017-01-19 12:49 UTC, ficristo commented on src/extensions/default/JavaScriptCodeHints/main.js
> +        CommandManager.register("Rename", "refactor.rename", handleRename);
You should add the string in `command/Commands.js` instead of using the string explicit.

2017-01-19 12:54 UTC, ficristo commented
From the code, this seems to work only for javascript files. I assume languages that derive from javascript in CodeMirror are NOT supported (for example json, typescript, ...)
Is it possible for extensions to easily override this behaviour so to support other languages?

2017-01-19 14:40 UTC, swmitra commented
@ficristo Yes, it's targeted for javascript mode.  So if CM identifies any block of code as javascript,  this would work there.  That includes script blocks in html,  any modes derived from JS by CodeMirror.  BTW,    is there any extension available today which implements this feature?

2017-01-19 14:40 UTC, swmitra commented
@ficristo Yes, it's targeted for javascript mode.  So if CM identifies any block of code as javascript,  this would work there.  That includes script blocks in html,  any modes derived from JS by CodeMirror.  BTW,    is there any extension available today which implements this feature?

2017-01-22 10:15 UTC, abose commented
@swmitra  Can you post a gif of how this works?

2017-01-22 13:34 UTC, swmitra commented
@abose I am not able to post a gif right now as I dont have access to any computer for a few days.  But what you can do is - put the cursor on top of the token you want to rename.  Then press ctrl+r . This will put selection on all the occurrences after doing a scope analysis.  Now just type the new name.  You will see multi cursor in action and should be able to rename all the occurrences.

2017-01-23 09:51 UTC, abose commented
👍 Cool feature

2017-01-30 18:59 UTC, ficristo commented
> is there any extension available today which implements this feature?

Looking at #11658 maybe [ternific](https://github.com/MiguelCastillo/Brackets-Ternific)?

2018-01-28 18:34 UTC, closed without merging