Added Extension Sorting capability according to downloads and last published date
adobe/brackets pull request #13080
Opened 2017-02-06 08:14 UTC by saurabh95

Now on opening the Extension Manager, a drop-down is shown on the left side of the search bar, which indicates the sorting of extensions according to the selected criteria(currently sort methods available are  Last Updated and Download Count), on change of the selection we store the the changed selection in the preferences and if the Extension Manager is invoked again, then we use the same sorting criteria which was selected by user earlier. The sorting is available for Available and Theme Extensions.

2017-02-06 09:16 UTC, petetnt reviewed
Mostly LGTM, needs tests 👍

2017-02-06 09:16 UTC, petetnt commented on src/extensibility/ExtensionManagerViewModel.js
> +            .filter(function (entry) {
There seems to be some redundancy here, seems like same could be achieved with:

``` js
return entry.registryInfo && entry.registryInfo.metadata;
```

Do correct me if I am wrong 👍

2017-02-06 09:47 UTC, ficristo commented
Nice! I think @zaggino and @dnbard could have some opinions on this.
See @dnbard extension: https://github.com/dnbard/brackets-extension-rating

I have two doubts:
- why we should threat the installed tab differently?
- `registry_utils` comes from brackets-registry: I guess it is necessary to change it but it seems to me it should be more "self contained" (= don't `require` Brackets code)

2017-02-06 11:46 UTC, saurabh95 commented
@ficristo the installed tab is treated differently as we do not have the download count of the installed extensions in the installInfo, and also currently the sorting of installed extensions is done according to the update available.
Yeah we can isolate the registry_utils from Brackets code, we can pass the preference as the argument.

2017-02-06 12:00 UTC, saurabh95 commented on src/extensibility/ExtensionManagerViewModel.js
> +            .filter(function (entry) {
yeah that can be changed :)

2017-02-06 16:16 UTC, saurabh95 commented
@ficristo @petetnt Addressed review comments and also added some tests.

2017-02-09 22:40 UTC, petetnt commented
Great stuff @saurabh95!

Some issues I spotted:

1. For me the extension manager opens on Installed page and the sort by-toggle is visible (and does nothing). Needs similar check to https://github.com/adobe/brackets/pull/13080/files#diff-3491ce7bb262eb073c8aabc3d3e064c0R376 when opening the window too.

2. The sort toggle breaks the layout with really narrow windows (but the search bar does it too). Feel free to disregard / bump to another issue.
![image](https://cloud.githubusercontent.com/assets/7641760/22806174/757b6da0-ef29-11e6-954d-5fb4b518955b.png)

3. The icons for download counts don't seem to work on Windows (10)
![image](https://cloud.githubusercontent.com/assets/7641760/22806196/8bd960b6-ef29-11e6-9f85-dbb7de57ceb2.png)

2017-02-09 22:45 UTC, petetnt requested changes
Reviewed again, couple of small issues, otherwise LGTM 👍

2017-02-09 22:45 UTC, petetnt commented on test/spec/ExtensionManager-test.js
> +                });
A simple check could be added that Brackets actually renders the `totalDownloads` to the UI 👍

2017-02-10 10:37 UTC, ficristo commented on src/extensibility/registry_utils.js
> +            if (sortBy !== "publishedDate") {
Not a big deal, but in general I prefer if you spell out all cases:
```js
if (sortBy === "downloadCount") {
} else if (sortBy === "publishedDate") {
} else {
  console.error("Unknown sortBy " + sortBy ". Defaults to....")
}
```
Or something like this.

2017-02-10 10:38 UTC, ficristo approved these changes
I didn't test this so I trust @petetnt.
But in general seems good.

2017-02-13 04:21 UTC, saurabh95 commented
@petetnt I have added a test for checking downloadCount in view and also added a check for active tab on launch of Extension Manager to hide/show the sort option, regarding the download icon, I will replace it with an image.

2017-02-20 06:07 UTC, swmitra approved these changes
Good stuff @saurabh95 👍

2017-02-20 06:12 UTC, saurabh95 commented
A screenshot with the new icon. 

![untitled](https://cloud.githubusercontent.com/assets/5630113/23113927/9bf40254-f761-11e6-9ce8-83ddfb7c5ba4.png)

2017-02-20 06:12 UTC, swmitra commented
Merging Now with the new Icon.

2017-02-20 06:12 UTC, merged