Sync code hint font size with code view font size
adobe/brackets pull request #13091
Opened 2017-02-10 08:38 UTC by swmitra

This PR enhances Brackets user experience by syncing the codehint font-size with code view font size. This was a problem in high dpi monitors ( WQHD and above ), where code hints were not readable with the current font-size. With this PR , when user changes code view font size, code hint font size also gets changed accordingly.

2017-02-10 10:20 UTC, ficristo commented
In case of JS hints the icon doesn't look good.
<img width="547" src="https://cloud.githubusercontent.com/assets/10583268/22823147/a70dad02-ef82-11e6-991c-492709028f2b.png">

2017-02-10 10:27 UTC, ficristo requested changes
I would like to see at least the documentation fixed.

2017-02-10 10:27 UTC, ficristo commented on src/view/ViewCommandHandlers.js
>       * @param {boolean} important Is a flag to make the style property !important
`cssRule` and `cssText` aren't documented.

2017-02-10 10:27 UTC, ficristo commented on src/view/ViewCommandHandlers.js
> +        var styleStr = cssText || StringUtils.format("{0}: {1} {2}", name, value, important ? " !important" : "");
I believe you can remove the space between this two parameters `{1} {2}`.

2017-02-10 10:27 UTC, ficristo commented on src/view/ViewCommandHandlers.js
> +     * Adds a new embeded style top sync code-hint font size with codeview font size
`fontSize` is not documented

2017-02-10 10:27 UTC, ficristo commented on src/view/ViewCommandHandlers.js
> +        _addDynamicProperty(DYNAMIC_CODEHINT_FONT_STYLE_ID, "font-size", fontSize, true, ".codehint-menu .dropdown-menu li a", styleStr);
You need to pass the values `font-size`, `fontSize` and `true` but they aren't actually used.
Perhaps it's personal style but it doesn't seems good.

2017-02-12 17:22 UTC, petetnt commented on src/view/ViewCommandHandlers.js
> +        _addDynamicProperty(DYNAMIC_CODEHINT_FONT_STYLE_ID, "font-size", fontSize, true, ".codehint-menu .dropdown-menu li a", styleStr);
I think `function _addDynamicProperty(propertyID, options)` would make more sense (where options would be an object of `{ name, value, important, cssRule, cssText }` etc.)

2017-02-13 04:56 UTC, swmitra commented
Thanks a lot @ficristo for the quick review 👍  I will update the PR soon.

2017-02-13 19:50 UTC, MiguelCastillo commented
Question around the approach.  Adding the a method specific for code hints seems reasonable, but I am not sure how that will scale if we had to add more methods for different parts of the UI.  Is there a way we can leverage CSS for the fonts size/type?

2017-03-07 07:08 UTC, swmitra commented
@MiguelCastillo Good point to consider 👍. 
I had tried the most generic approach by increasing the base font size for body. In that way we can increase and sync the font size in other panes like project panel and Dialogs as well. But it's not convincing use case for every one. In fact most of the people I spoke with wanted to increase just the code view font size and nothing else. I will hold this PR for now and lets ask other developers about the actual feature scope itself. Please let me know your opinion about the feature scope.

2017-03-07 07:24 UTC, zaggino commented
I'd say that while @MiguelCastillo 's point is valid, we should not get into the habit of stacking feature on top of feature in PRs which makes them not only very large but also increases the time which they take to merge, sometimes are these even never merged as authors get discouraged. So if @swmitra 's PR works and solves the problem it was meant to solve (without introducing new ones), we should merge it and open further suggestions as separate issues.

2017-03-07 07:51 UTC, swmitra commented
@ficristo We no longer use that icon in JS code hints. I am a bit confused as I don't see those icons in JS code hints, Can you please confirm once more?

2017-03-07 08:49 UTC, ficristo commented
@swmitra you are right. After I had disabled my extensions I don't see it anymore.

2017-03-07 10:48 UTC, swmitra commented
Thanks a lot @ficristo for quick confirmation 👍 . Can you please have a look at the changes again as I have tried to address the comments? @petetnt I have wrapped the parameters in a configuration object as per your suggestion, can you please have a look?

2017-03-07 15:20 UTC, swmitra commented
@MiguelCastillo Can you please check the implementation now? I just tried to make it extensible by using a less template.

2017-03-07 15:21 UTC, MiguelCastillo commented
yup i am checking now.  BTW - thank you for clarifying the use case.  It definitely helped me understand the scope of what we are accomplishing.  I am happy with what we got here :)

2017-03-07 15:36 UTC, MiguelCastillo commented on src/view/fontrules/font-based-rules.less
> +    max-height: @maxvisibleitems * @lineheight !important;
how does line height affect this when the fontsize is define in `px` vs `em`?

2017-03-07 15:40 UTC, MiguelCastillo commented
I like what you have done here!  very interesting!  I just had a question regarding the max-height value and how it is affected when font size is specified with different units.

2017-03-08 07:46 UTC, swmitra commented
@MiguelCastillo I had made core template calculations unit agnostic. Also I had to introduce an additional step to convert only em to px. Rest all units like pt, rem and px works well with this implementation. 
Thanks a lot for bringing the point up as it finally resulted in a better implementation 👍.

Please check the code and try out the implementation and let me know if see any issues.

2017-03-08 21:37 UTC, MiguelCastillo commented
@swmitra  yeah - this is good to merge for me.  I am not sure if there are any TODOs pending, are there?

2017-03-09 06:02 UTC, swmitra commented
@ficristo Can you please have a look now?

2017-03-09 09:18 UTC, ficristo commented
@MiguelCastillo review is more than enough for me.

2017-03-09 09:18 UTC, ficristo approved these changes

2017-03-09 12:59 UTC, merged

2017-09-25 22:58 UTC, chylex commented
Is there any way to revert this? It feels like I can see way fewer hints than I used to, and any code hints that include documentation look misaligned, so I'd rather go back to the default font size.