#11801 - Restricted Font Size Input To Only Valid Entries
adobe/brackets pull request #13123
Opened 2017-02-24 22:28 UTC by nyteksf

Related to #11801.

Text was able to be inputted into Font Size within Themes Settings (e.g. "View > Themes...") even when it included non-ASCII characters or was in a generally unusable format.
 
Corrected this issue by ensuring all font sizes are to begin with a number, and are completed by either "px" or "em" only. 'Done' button remains disabled until said format is adhered to correctly--at which time the functionality of said button becomes restored that it may be saved.

@zaggino

2017-02-24 22:56 UTC, zaggino requested changes
just a first quick look without testing, let me know when you'll look at the comments

2017-02-24 22:56 UTC, zaggino commented on src/config.json
> +        "healthDataServerURL": "https://health.brackets.io/healthDataLog"
you need to revert this change (it applies automatically after doing npm install, but we don't want it in PRs)

2017-02-24 22:56 UTC, zaggino commented on src/view/ThemeSettings.js
> +                var btn = document.getElementById("done");
add `document` to the globals please: https://github.com/adobe/brackets/blob/master/.eslintrc.json#L52

2017-02-24 22:56 UTC, zaggino commented on src/htmlContent/themes-settings.html
> +        <button class="dialog-button btn primary" id="done" data-button-id="save">{{Strings.DONE}}</button>
id `done` is not very good, you should be more specific when introducing id's, something like `theme-settings-done-btn` would be more appropriate

2017-02-24 22:56 UTC, zaggino commented on src/htmlContent/themes-settings.html
> +                    <input type="text" id="font-family-input" data-target="fontFamily" value="{{settings.fontFamily}}">
don't need to introduce id's here, you can use `.on("input", "[data-target=fontFamily]", function () {`
https://www.w3schools.com/jquery/sel_attribute_equal_value.asp

2017-02-24 22:56 UTC, zaggino commented on src/view/ThemeSettings.js
> +                var $input = $target.val();
`$` prefix for variables indicates that it's a jquery (or a DOM) element
in this case `$input` is a string and should really be named `input` or even better `targetValue`

2017-02-24 22:56 UTC, zaggino commented on src/view/ThemeSettings.js
> +                    ($input.length === 0) ? btn.disabled=false : btn.disabled=true;
`btn.disabled = $input.length !== 0` is better

2017-02-24 22:56 UTC, zaggino commented on src/view/ThemeSettings.js
> +                }else{
`}else{` after `return` doesn't make sense, just close the if with `}` and continue normally

2017-02-24 23:29 UTC, zaggino commented
also make sure command `grunt eslint` in your branch doesn't throw any errors

2017-02-25 13:20 UTC, ficristo commented on .eslintrc.json
> +        "document": false,
Sorry for mixed signals, but please revert this.
`document` is a generic word and in Brackets usually refer to the Document object.
I think you can go with jquery here, can't you? `$("#theme-settings-done-btn")`

2017-02-25 13:21 UTC, ficristo commented
Out of curiosity, any reason to not use the pattern attribute?

2017-02-26 05:32 UTC, mohanad1980 commented
hello can you contact me mohanad.rahimi1@gmail.com

2017-02-27 08:24 UTC, nyteksf commented on .eslintrc.json
> +        "document": false,
Sorry for the delay--I've been busy with moving, although wanted to finish and reply. That said,, yes, I can use jQuery here. Good point. And thanks for clarifying. This is my first pull request; let alone open source patch. I wasn't sure if I should use jQuery as little as possible as noobish as that sounds. This turned out to be a simple fix.  :)

2017-02-27 08:28 UTC, nyteksf commented
Thanks, guys, for your speedy replies. To reply to you now myself: that HTML5 pattern attribute was actually wholly new to me. I've learned a bunch in a few reviewer comments. I have to agree with you both that "pattern" is much better. Thanks again. Please feel free to let me know if anything else would be problematic.

2017-02-27 08:37 UTC, zaggino approved these changes

2017-02-27 08:38 UTC, zaggino commented
fine with me, @ficristo ?

2017-02-27 08:54 UTC, ficristo commented
It seems fine for me.
Ideally we could expose this regex: https://github.com/adobe/brackets/blob/d6ae906810b8e6afb43c88edcf0397b1dc1b0119/src/view/ViewCommandHandlers.js#L300
and use it on the html.

2017-02-27 09:05 UTC, zaggino commented
@nyteksf to do what @ficristo wrote, you'd have to edit this file https://github.com/nyteksf/brackets/blob/9a6f12cf259276ebd163e70266030377df67eb2b/src/view/ViewCommandHandlers.js and make this https://github.com/adobe/brackets/blob/d6ae906810b8e6afb43c88edcf0397b1dc1b0119/src/view/ViewCommandHandlers.js#L300 an exported variable. 

Then here https://github.com/nyteksf/brackets/blob/9a6f12cf259276ebd163e70266030377df67eb2b/src/view/ThemeSettings.js#L82 you'd pass the `ViewCommandHandlers.validFontRegex` (or however you call it) to Mustache and render it here https://github.com/nyteksf/brackets/blob/9a6f12cf259276ebd163e70266030377df67eb2b/src/htmlContent/themes-settings.html#L33 like `{{ fontPattern }}` or something

Hope that's clear enough, @ficristo correct me if I'm wrong

2017-02-27 12:25 UTC, petetnt commented
LGTM, but we should accept at least `rem` values and percentages too, no?

2017-02-27 12:32 UTC, zaggino commented
Current regexp which is used deeper ( https://github.com/adobe/brackets/blob/d6ae906810b8e6afb43c88edcf0397b1dc1b0119/src/view/ViewCommandHandlers.js#L300 ) seems to only allow `px|em` ... do we want to change this?

2017-03-03 01:35 UTC, nyteksf commented
Thank you, guys. I have had to fiddle around with the RegExp a little to make the prescribed changes work. It seems backslashes need to be escaped--having tried the various remedies in the docs--and this causes the RegExp constructor used for the non-exported segment to be passed something unintended. Likewise, to use RegExp literally, it seems would require `.slice()`ing off the foreslashes. That said, I have switched it to `"[0-9.]"` instead of `"\d"`. But everything else should be as asked for to my awareness. Please let me know what you think in any case. Thanks very much. :)

2017-03-03 01:44 UTC, zaggino requested changes
just a few small changes that are of stylistic nature and I believe we're good to merge this

2017-03-03 01:44 UTC, zaggino commented on src/htmlContent/themes-settings.html
> +                    <input type="text" pattern="{{ settings.validFontSizeRegExp}}" data-target="fontSize" value="{{settings.fontSize}}">
missing space before `}}`

2017-03-03 01:44 UTC, zaggino commented on src/view/ThemeSettings.js
> +    var validFontSizeRegExp = ViewCommandHandlers.validFontSizeRegExp;
constant definitions should always be on top

2017-03-03 01:44 UTC, zaggino commented on src/view/ThemeSettings.js
> +// Select the correct theme.
invalid whitespace change

2017-03-03 01:44 UTC, zaggino commented on src/view/ViewCommandHandlers.js
> +     var validFontSizeRegExpStr = "^[0-9.]+(px|em)$"; // Need RegExp string to be exported for compatibility with HTML5 pattern attribute.
constant definitions should always be on top (after import declarations) and not between functions, also needs a comment, something like:
```
/*
 * Font sizes should be validated by this regexp
 */
```

2017-03-03 02:22 UTC, nyteksf commented
Whoops! Well, okay: there you go. Thanks again for a speedy reply!

@zaggino

2017-03-03 02:31 UTC, zaggino commented
Testing this, it allows input like:
`12.00.00px`
can we please change regexp to be maybe:
`"^[0-9]+(\.[0-9]+)?(px|em)$"`

2017-03-03 02:33 UTC, zaggino commented
Done with testing, just change this one and I'm merging this (promise 😄 )

2017-03-03 05:16 UTC, nyteksf commented
Okay. I'm going out on a limb here: please do correct me if I am wrong. I added your change to the original deeper RegExp. Then in doing my own testing, I had found that it worked almost perfectly. The RegExp in question, however, didn't handle cases like "`.5em`", without first adding a zero to make it like "`0.5em`". It isn't a problem, I'm sure. My change seems like a small change indeed--but I figured I could change it. And now it should handle cases like "`0.5em`" as well as "`.5em`". Please let me know if it works as it seems to on my end. And thanks again for all your help.  :)))

@zaggino

2017-03-03 05:28 UTC, nyteksf commented
Nevermind. I found a flaw. Changing back to original.

2017-03-03 05:38 UTC, nyteksf commented
Okay, @zaggino. My fingers are crossed this time. I'm sending my final changes over your way if you'll please take another look now.  :)

2017-03-03 06:25 UTC, zaggino commented
Oh, github new features are superb, did a small change to your regexp through the web - when inside a string you need to escape `\.` like this `\\.` - otherwise an expression `12a5px` would be valid, I've fixed that

2017-03-03 06:30 UTC, zaggino commented
Looks good to me now. I think all comments above have been considered so I'm merging this.
Thanks a lot for the PR a for sticking with it to the end, hope we'll meet again on some other one.
Cheers!

2017-03-03 06:30 UTC, merged