Remove normalizeFilename function
adobe/brackets pull request #13147
Opened 2017-03-03 18:22 UTC by ficristo

Quick hack for https://github.com/adobe/brackets/issues/12744, I doubt this is the correct way to fix.
I am only interested to see if this could solve the crashes people are experiencing.

/cc @zaggino

2017-03-03 19:05 UTC, zaggino commented
This construct
```
var fileName = fileInfo.name;
if (ternServer.projectDir && fileName.indexOf(ternServer.projectDir) === -1) {
  fileName = ternServer.projectDir + fileName;
}
```
repeats itself if I have counted right and not missed any difference 5 times over the diff, perhaps
```
function getNormalizedFilename(fileInfo, ternServer) {
  return ...
}
```
and use `var fileName = getNormalizedFilename(fileInfo, ternServer);` would be a bit nicer

2017-03-03 19:07 UTC, ficristo commented
Sure! If this fixes the crashes I'll refactor like that.

2017-03-03 19:07 UTC, zaggino commented
Anyway, were you able to replicate anything, or is this just a hinch? If it doesn't break any tests I think we could merge this for time being as https://github.com/adobe/brackets/pull/11948 doesn't seem to be moving much...

2017-03-03 19:09 UTC, ficristo commented
Since people repored crashes in 1.8 that weren't in 1.8 this is the only thing that comes to my mind.
So yes, this is only an hinch...
The tests pass.

2017-03-03 19:12 UTC, zaggino commented
I have a project which, while working on it, definitely crashes Brackets, but I can't replicate this. Sometimes after 5 minutes, sometimes after an hour. So it'd vote the approach of merging it and seeing if there's any change in the reports.

2017-03-03 19:39 UTC, zaggino requested changes
refactor before merge

2017-03-04 17:29 UTC, ficristo commented
Refactored. After running tests again, they are quite flaky. But I'm not sure if it is because our testsuite or because my PR...

2017-03-06 02:03 UTC, zaggino commented on src/extensions/default/JavaScriptCodeHints/tern-worker.js
> +                if (ternServer.projectDir && fileName.indexOf(ternServer.projectDir) === 0) {
if you don't mind one last change, for future readability, I'd extract this to `_getDenormalizedFilename` as this basically reverts `_getNormalizedFilename` if I'm not mistaken

2017-03-06 02:04 UTC, zaggino commented
Hi @ficristo , I've run the tests and they all pass on my machine so that thing is fine.
Just one minor thing (commented above) and I'd merge this if nobody doesn't want to add anything.

2017-03-06 19:44 UTC, ficristo commented on src/extensions/default/JavaScriptCodeHints/tern-worker.js
> +                if (ternServer.projectDir && fileName.indexOf(ternServer.projectDir) === 0) {
Done

2017-03-06 20:15 UTC, merged

2017-03-06 20:15 UTC, zaggino commented
👍