CSS code hints in 'style' attribute value context
adobe/brackets pull request #13270
Opened 2017-04-05 08:58 UTC by swmitra

This PR enables Brackets to provide CSS code hints property-value code hints while editing 'style' attribute value in 'html' mode. The implementation contains minor tweaks to the CSSUtils module to recognize this as 'css' context as CodeMirror doesn't understand the 'style' attribute value as 'css' context. 

Adding @ingorichter @petetnt @zaggino and @ficristo for review, but others can also join 👍

2017-04-06 18:43 UTC, ficristo commented
Sorry but I don't have enough interest in this feature to review it.
Maybe @humphd is interested?

2017-04-07 05:20 UTC, swmitra commented
@humphd Can you please have a look at this PR?

2017-04-09 06:47 UTC, ingorichter commented on src/language/CSSUtils.js
> +                // tagInfo is required to aquire the style attr value
nit: indent level

2017-04-09 06:49 UTC, ingorichter commented
@swmitra it would be beneficial to have some unit tests for the new functionality. This is complex and might break accidentally.

2017-04-09 10:23 UTC, swmitra commented
Sure @ingorichter. I will add some functional tests in this PR and ping you.

2017-04-10 15:28 UTC, petetnt requested changes
Change set LGTM with a small nit. 

However it doesn't seem to handle multiline styles yet:

```html
<div style="background-color: red; // works here
color: white; // doesn't work here>Foo</div>
```

It would be also great if it worked on JSX context (`<div style={{backgroundColor: red}}`>Hey</div>`) but that's more a feature request :)

2017-04-10 15:28 UTC, petetnt commented on src/language/CSSUtils.js
> +                // tagInfo is required to aquire the style attr value
Indent

2017-04-12 07:04 UTC, swmitra commented
@ingorichter I have added some unit tests in my last commit.
@petetnt Fixed the multiline attribute value issue and corrected indentation. 
Can you guys please review it once more? ☺️

2017-04-13 04:43 UTC, zaggino approved these changes
- checked the code, seems good
- checked the unit tests, present & passing
- tested the feature manually, working fine

2017-04-13 04:44 UTC, merged

2017-04-13 21:25 UTC, ingorichter commented
I'm too late :-/