Added UI for search History
adobe/brackets pull request #13302
Opened 2017-04-13 05:37 UTC by saurabh95

The UI is inspired from https://trello.com/c/IzACddEv/344-s-find-recent-search-history with minor tweaks.

2017-04-16 17:38 UTC, ficristo commented
I leave the review for someone else here.
I only have one question: when you select an item from the dropdown list and then reopen the list, only the item selected is visible. Is this expected?
If I need to change the item, I have to clear the content of the search box and only then I'm able to see other items in the dropdown list, which is a bit of a pain.

Do you still have an UI / UX designer that can review these kind changes ?

2017-04-17 03:42 UTC, saurabh95 commented
@ficristo Actually I have added a filtering in the dropdown, if there is some text in the search field and then we try to open dropdown, then only elements in dropdown which have that string as its substring would be visible.

2017-04-17 04:13 UTC, saurabh95 commented
@ficristo discussed it with Rajnish, he also feels that removing the filtering would be better, so now whole search history is visible irrespective of content in the search field

2017-04-17 17:03 UTC, petetnt requested changes
Added a few comments, mostly looks really great 👍

2017-04-17 17:03 UTC, petetnt commented on src/search/FindBar.js
> +                } else if (!$(".quick-search-container").is(':visible')) {
This can be just `else`, right?

2017-04-17 17:03 UTC, petetnt commented on src/search/FindBar.js
> +                        searchHistory.unshift($('#find-what').val());
Maybe cache the `#find-what` value to a variable

2017-04-17 17:03 UTC, petetnt commented on src/search/FindBar.js
> +                } else if ($(".quick-search-container").is(':visible')) {
`${".quick-search-container"}` could be cached to a variable

2017-04-17 17:03 UTC, petetnt commented on src/search/FindBar.js
> +                    } else if (!$(".quick-search-container").is(':visible')) {
Use the cached variable here too (see the previous review comment)

2017-04-17 17:03 UTC, petetnt commented on src/search/FindBar.js
> +        this.$searchField = $("input#find-what");
This part (L430-L432) with nested `this.$searchField` looks a bit scary, maybe refactor it to use some named variables instead.

2017-04-17 17:03 UTC, petetnt commented on src/search/FindBar.js
> +                self.$("#find-what").focus();
What's the difference between `self.$("#find-what")` and `$("#find-what")`?

2017-04-24 03:03 UTC, swmitra commented on src/search/FindBar.js
> +                        searchHistory.unshift($('#find-what').val());
I second @petetnt. Value of `#find-what` should be assigned to a variable while initiating the search session. Whole session should refer to the same value for navigation.

2017-04-24 04:19 UTC, saurabh95 commented on src/search/FindBar.js
> +                self.$("#find-what").focus();
Actually there are chances of having multiple find bars present (one is closing, other might be opening), so there can be multiple `$("#find-what")`, so to add context to it we use `self.$("#find-what")`

2017-04-24 04:51 UTC, swmitra approved these changes
LGTM 👍

2017-04-24 04:52 UTC, swmitra commented
@petetnt Once you approve, I will merge this PR 😄

2017-04-24 12:21 UTC, petetnt approved these changes
LGTM codewise, haven't had the time to retest the functionality though.

2017-04-24 12:54 UTC, swmitra commented
@saurabh95 Great work :+1

2017-04-24 12:54 UTC, swmitra commented
Merging...

2017-04-24 12:54 UTC, merged