Saurabh95/encoding support
adobe/brackets pull request #13412
Opened 2017-06-02 06:18 UTC by saurabh95

2017-06-02 07:21 UTC, petetnt commented
Oh cool, this is very nice 🙌

2017-06-20 09:37 UTC, swmitra commented on src/document/Document.js
> +    Document.prototype.reload = function () {
You might want to use a separate promise like what we do in other places.

2017-06-20 10:47 UTC, swmitra requested changes

2017-06-20 10:47 UTC, swmitra commented on src/editor/EditorStatusBar.js
> +        encodingSelect.$button.css("width", "auto");
Define it once in CSS.

2017-06-20 10:47 UTC, swmitra commented on src/document/DocumentCommandHandlers.js
> +            newFile._encoding = doc.file._encoding;
We can actually write the explicitly selected encoding for path even before we do a 'getFileForPath()'. In that way our existing logic of picking up a user preferred encoding will take care of the rest. With the current code we are actually missing the user preference completely for the new file and in next launch of the new file, encoding detection might result in a corruption where the user might have to select a suitable encoding again.

2017-06-21 08:21 UTC, swmitra approved these changes

2017-06-23 09:42 UTC, merged