Change Preact require to thirdparty/preact
adobe/brackets pull request #13664
Opened 2017-09-06 07:02 UTC by boopeshmahendran

2017-09-07 13:07 UTC, saurabh95 requested changes

2017-09-07 13:07 UTC, saurabh95 commented on test/SpecRunner.js
> +            "thirdparty/preact":            "preact-compat",
nit. the colon should be in the same column as the lines above and below.

2017-09-07 13:07 UTC, saurabh95 commented on test/spec/FileTreeView-test.js
> +        PTU               = require("thirdparty/preact-test-utils"),
I would recommend having a more readable name instead of `PTU`, `PreactTestUtils` may be.

2017-09-12 13:35 UTC, swmitra approved these changes

2017-09-12 13:36 UTC, merged