Update CSS at-rules
adobe/brackets pull request #14013
Opened 2018-01-05 16:03 UTC by valtlai

Add @counter-style and @font-feature-values.
(Align colons.)

2018-01-08 20:10 UTC, petetnt commented on src/extensions/default/CSSAtRuleCodeHints/AtRulesDef.json
> +    "@font-feature-values": "Define common names in font-variant-alternates for feature activated differently in OpenType.",
[MDN}(https://developer.mozilla.org/en-US/docs/Web/CSS/%40font-feature-values) phrases this as `Defines a common name in font-variant-alternates for features activated differently in OpenType.`, not quite sure which one is more correct though 
¯\\\_(ツ)_/¯

2018-01-08 20:23 UTC, valtlai commented on src/extensions/default/CSSAtRuleCodeHints/AtRulesDef.json
> +    "@font-feature-values": "Define common names in font-variant-alternates for feature activated differently in OpenType.",
Hmm, these descriptions are from [another MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule).

2018-01-08 20:36 UTC, petetnt commented on src/extensions/default/CSSAtRuleCodeHints/AtRulesDef.json
> +    "@font-feature-values": "Define common names in font-variant-alternates for feature activated differently in OpenType.",
Then it's good enough for me (maybe fix them in MDN too? 😂 )

2018-01-08 20:36 UTC, petetnt approved these changes

2018-01-08 20:51 UTC, valtlai commented on src/extensions/default/CSSAtRuleCodeHints/AtRulesDef.json
> +    "@font-feature-values": "Define common names in font-variant-alternates for feature activated differently in OpenType.",
Made it a bit more consistent by adding *-s*. 😇

2018-01-13 16:19 UTC, ficristo requested changes
Fix the test.
Otherwise LGTM.

2018-01-14 11:42 UTC, valtlai commented
Fixed the test.

2018-01-14 19:18 UTC, ficristo approved these changes

2018-01-14 19:19 UTC, merged

2018-01-14 19:23 UTC, ficristo commented
Thank you!