Appending Remote word in working set
adobe/brackets pull request #14321
Opened 2018-05-11 05:02 UTC by navch

Issue Fixed https://github.com/adobe/brackets/issues/14309

2018-05-11 08:56 UTC, shubhsnov commented on src/utils/ViewUtils.js
> +
See if we can use useIconProviders and useClassProviders from Working Set View for this as well

2018-05-11 09:17 UTC, shubhsnov commented on src/utils/ViewUtils.js
> +
ping @swmitra  for guidance. I believe the "Remote" word can be added to the :after of a class and then that class can be registered with working set view.

2018-05-12 04:05 UTC, swmitra commented
We should use the file tree decoration model by providing icon and class provider. It should be a pure CSS solution in decorating the remote file entries.

2018-05-12 04:13 UTC, swmitra requested changes
Let's use just the protocol name as marker. It's more friendly for a developer instead of calling Remote. This can be done using a pseudo selector with content set to protocol name.

2018-05-12 22:15 UTC, navch commented
@swmitra Review comment addressed. Please have a look now.

2018-05-14 09:13 UTC, shubhsnov commented
@navch  I think we should add prototype.name in all File, InMemoryFile and RemoteFile and then check against that directly

2018-05-14 11:08 UTC, boopeshmahendran commented
Could we check `constructor.name` like [this](https://github.com/adobe/brackets/blob/master/src/extensions/default/NavigationAndHistory/main.js#L604)?

2018-05-15 13:40 UTC, swmitra commented
Closing this PR as #14330 adds protocol badge to all remote file entries in working set and recent file list.

2018-05-15 13:40 UTC, closed without merging