Disabeling working set context menu for remote files
adobe/brackets pull request #14326
Opened 2018-05-12 07:43 UTC by navch

Issue Fixed : - Disabling four commands Save, Show in Explorer, Show in the file tree, Rename.

2018-05-12 16:31 UTC, swmitra requested changes
It checks for currently viewed file only. But context menu event can be triggered on any file listed in working set. So, if the currently viewed file is not a RemoteFile, but user has right clicked on a RemoteFile, we would still end up showing all these commands.

2018-05-12 18:08 UTC, navch commented
When we open the context menu on any file then first it switches active file viewing then it opens the context menu. As you can check this [here](https://github.com/adobe/brackets/blob/master/src/command/DefaultMenus.js#L53)

2018-05-15 10:50 UTC, shubhsnov commented
👍 LGTM

2018-05-15 11:33 UTC, swmitra approved these changes

2018-05-15 11:34 UTC, merged