Add styles for stickyhighlight feature in livepreview
adobe/brackets pull request #14546
Opened 2018-09-24 11:41 UTC by boopeshmahendran

2018-09-24 14:32 UTC, vickramdhawal requested changes

2018-09-24 14:32 UTC, vickramdhawal commented on src/LiveDevelopment/Agents/RemoteFunctions.js
> +                window.document.addEventListener("mouseover", onDocumentHover);
I think you would need to listen in the capture phase.

2018-09-24 14:32 UTC, vickramdhawal commented on src/LiveDevelopment/Agents/RemoteFunctions.js
> +                window.document.addEventListener("mouseover", onDocumentHover);
Also, when updateConfig is called, the event listener should be attached even at that time and disengaged when the config changes again.

2018-09-25 13:28 UTC, boopeshmahendran commented
@vickramdhawal Thanks for the quick review. I have addressed the review comments

2018-09-25 16:10 UTC, swmitra reviewed
Border would potentially hide/override any Broder used in the actual UI. The ideal way to highlight is either by using a outline or drawing an overlay div by constructing an overlay pane on top of the entire page. Then use element from point of mouse event and use the targets bounding client rect to draw the highlight overlay. Usage of the overlay pane is required to prevent click on an actual link or button.

2018-09-25 16:36 UTC, boopeshmahendran commented
Thanks for the review @swmitra The approach you have described is the exact one followed as you can see [here](https://github.com/adobe/brackets/blob/aff17281c33762a2070aea93a58249ec9f1ccb3f/src/LiveDevelopment/Agents/RemoteFunctions.js#L288) . The border is on the overlay div.

2018-09-25 16:57 UTC, swmitra commented
But still not in an overlay pane. However use outline and the actual elements bounding box for positioning the highlight overlay and styling.

2018-09-26 02:48 UTC, vickramdhawal commented
The current implementation follows the existing approach. Are you suggesting to introduce an overlay pane overall for both the highlight modes ?

2018-09-26 04:34 UTC, vickramdhawal approved these changes

2018-09-26 04:35 UTC, merged